// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: pruebas/final_flex/analizador.flex

// package com.persistencia.analizadorLexicoFlex;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;
import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class Analizador implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\2\0\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\12\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\0\22\27\1\30\7\27\1\31"+
    "\1\32\1\33\1\0\1\34\1\0\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\27\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\27\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\27\1\64"+
    "\1\65\1\66\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\2\23\1\24\1\25"+
    "\16\23\1\26\1\1\1\27\1\30\1\0\1\31\1\0"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\2\1\40"+
    "\1\0\1\41\7\23\1\42\4\23\1\43\15\23\1\44"+
    "\1\45\12\23\1\46\1\23\1\47\1\23\1\50\1\51"+
    "\15\23\1\52\2\23\1\53\4\23\1\54\10\23\1\55"+
    "\4\23\1\56\1\57\2\23\1\60\12\23\1\61\1\62"+
    "\1\63\4\23\1\64\4\23\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\73\1\23\1\74\1\75\1\76\4\23"+
    "\1\77\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\334\0\67\0\u0113"+
    "\0\67\0\67\0\u014a\0\u0181\0\67\0\u01b8\0\67\0\u01ef"+
    "\0\u0226\0\67\0\67\0\67\0\u025d\0\67\0\u0294\0\u02cb"+
    "\0\67\0\67\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415"+
    "\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd"+
    "\0\67\0\u0604\0\67\0\67\0\334\0\67\0\u063b\0\67"+
    "\0\67\0\67\0\67\0\67\0\67\0\u0672\0\67\0\u06a9"+
    "\0\67\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a"+
    "\0\u0294\0\u0861\0\u0898\0\u08cf\0\u0906\0\u0294\0\u093d\0\u0974"+
    "\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c"+
    "\0\u0b63\0\u0b9a\0\u0bd1\0\67\0\u06a9\0\u0c08\0\u0c3f\0\u0c76"+
    "\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0294"+
    "\0\u0e2e\0\u0294\0\u0e65\0\u0294\0\u0294\0\u0e9c\0\u0ed3\0\u0f0a"+
    "\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2"+
    "\0\u10f9\0\u1130\0\u0294\0\u1167\0\u119e\0\u0294\0\u11d5\0\u120c"+
    "\0\u1243\0\u127a\0\u0294\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d"+
    "\0\u13c4\0\u13fb\0\u1432\0\u0294\0\u1469\0\u14a0\0\u14d7\0\u150e"+
    "\0\u0294\0\u0294\0\u1545\0\u157c\0\u0294\0\u15b3\0\u15ea\0\u1621"+
    "\0\u1658\0\u168f\0\u16c6\0\u16fd\0\u1734\0\u176b\0\u17a2\0\u0294"+
    "\0\u0294\0\u0294\0\u17d9\0\u1810\0\u1847\0\u187e\0\u0294\0\u18b5"+
    "\0\u18ec\0\u1923\0\u195a\0\u0294\0\u0294\0\u0294\0\u0294\0\u0294"+
    "\0\u0294\0\u0294\0\u1991\0\u0294\0\u0294\0\u0294\0\u19c8\0\u19ff"+
    "\0\u1a36\0\u1a6d\0\u0294\0\u0294";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\2\1\32\1\2\1\27\1\33\1\34"+
    "\1\35\1\36\1\37\2\27\1\40\2\27\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\2\27\1\47\1\50\2\27"+
    "\1\51\1\52\1\53\70\0\1\3\2\0\1\3\107\0"+
    "\1\54\41\0\6\55\1\56\23\55\1\57\34\55\10\0"+
    "\1\60\103\0\1\61\55\0\1\62\10\0\1\63\57\0"+
    "\1\64\6\0\1\65\61\0\1\66\4\0\1\67\60\0"+
    "\1\70\1\0\1\21\72\0\1\71\62\0\1\27\5\0"+
    "\2\27\3\0\30\27\24\0\1\27\5\0\2\27\3\0"+
    "\22\27\1\72\4\27\1\73\24\0\1\27\5\0\2\27"+
    "\3\0\16\27\1\74\1\27\1\75\7\27\24\0\1\27"+
    "\5\0\2\27\3\0\1\27\1\76\11\27\1\77\14\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\100\10\27"+
    "\1\101\11\27\24\0\1\27\5\0\2\27\3\0\13\27"+
    "\1\102\12\27\1\103\1\27\24\0\1\27\5\0\2\27"+
    "\3\0\13\27\1\104\2\27\1\105\11\27\24\0\1\27"+
    "\5\0\2\27\3\0\6\27\1\106\5\27\1\107\1\110"+
    "\12\27\24\0\1\27\5\0\2\27\3\0\1\27\1\111"+
    "\26\27\24\0\1\27\5\0\2\27\3\0\5\27\1\112"+
    "\22\27\24\0\1\27\5\0\2\27\3\0\23\27\1\113"+
    "\4\27\24\0\1\27\5\0\2\27\3\0\1\27\1\114"+
    "\16\27\1\115\2\27\1\116\4\27\24\0\1\27\5\0"+
    "\2\27\3\0\5\27\1\117\22\27\24\0\1\27\5\0"+
    "\2\27\3\0\22\27\1\120\2\27\1\121\2\27\24\0"+
    "\1\27\5\0\2\27\3\0\16\27\1\122\11\27\24\0"+
    "\1\27\5\0\2\27\3\0\10\27\1\123\17\27\70\0"+
    "\1\124\1\0\2\55\3\0\62\55\2\66\3\0\62\66"+
    "\21\0\1\125\66\0\1\27\5\0\2\27\3\0\20\27"+
    "\1\126\7\27\24\0\1\27\5\0\2\27\3\0\21\27"+
    "\1\127\6\27\24\0\1\27\5\0\2\27\3\0\16\27"+
    "\1\130\11\27\24\0\1\27\5\0\2\27\3\0\5\27"+
    "\1\131\22\27\24\0\1\27\5\0\2\27\3\0\21\27"+
    "\1\132\6\27\24\0\1\27\5\0\2\27\3\0\1\27"+
    "\1\133\26\27\24\0\1\27\5\0\2\27\3\0\6\27"+
    "\1\134\21\27\24\0\1\27\5\0\2\27\3\0\21\27"+
    "\1\135\6\27\24\0\1\27\5\0\2\27\3\0\22\27"+
    "\1\136\5\27\24\0\1\27\5\0\2\27\3\0\16\27"+
    "\1\137\11\27\24\0\1\27\5\0\2\27\3\0\20\27"+
    "\1\140\7\27\24\0\1\27\5\0\2\27\3\0\17\27"+
    "\1\141\10\27\24\0\1\27\5\0\2\27\3\0\22\27"+
    "\1\142\5\27\24\0\1\27\5\0\2\27\3\0\11\27"+
    "\1\143\16\27\24\0\1\27\5\0\2\27\3\0\25\27"+
    "\1\144\2\27\24\0\1\27\5\0\2\27\3\0\22\27"+
    "\1\145\5\27\24\0\1\27\5\0\2\27\3\0\3\27"+
    "\1\146\24\27\24\0\1\27\5\0\2\27\3\0\11\27"+
    "\1\147\4\27\1\150\11\27\24\0\1\27\5\0\2\27"+
    "\3\0\2\27\1\151\25\27\24\0\1\27\5\0\2\27"+
    "\3\0\22\27\1\152\5\27\24\0\1\27\5\0\2\27"+
    "\3\0\1\27\1\153\26\27\24\0\1\27\5\0\2\27"+
    "\3\0\11\27\1\154\16\27\24\0\1\27\5\0\2\27"+
    "\3\0\11\27\1\155\16\27\24\0\1\27\5\0\2\27"+
    "\3\0\11\27\1\156\16\27\24\0\1\27\5\0\2\27"+
    "\3\0\11\27\1\157\16\27\24\0\1\27\5\0\2\27"+
    "\3\0\22\27\1\160\5\27\24\0\1\27\5\0\2\27"+
    "\3\0\13\27\1\161\14\27\24\0\1\27\5\0\2\27"+
    "\3\0\1\27\1\162\26\27\24\0\1\27\5\0\2\27"+
    "\3\0\5\27\1\163\22\27\24\0\1\27\5\0\2\27"+
    "\3\0\21\27\1\164\6\27\24\0\1\27\5\0\2\27"+
    "\3\0\1\27\1\165\26\27\24\0\1\27\5\0\2\27"+
    "\3\0\5\27\1\166\22\27\24\0\1\27\5\0\2\27"+
    "\3\0\5\27\1\167\22\27\24\0\1\27\5\0\2\27"+
    "\3\0\1\27\1\170\26\27\24\0\1\27\5\0\2\27"+
    "\3\0\13\27\1\171\2\27\1\172\11\27\24\0\1\27"+
    "\5\0\2\27\3\0\15\27\1\173\12\27\24\0\1\27"+
    "\5\0\2\27\3\0\12\27\1\174\15\27\24\0\1\27"+
    "\5\0\2\27\3\0\15\27\1\175\6\27\1\176\3\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\177\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\13\27\1\200\14\27"+
    "\24\0\1\27\5\0\2\27\3\0\23\27\1\201\4\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\202\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\203\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\4\27\1\204\23\27"+
    "\24\0\1\27\5\0\2\27\3\0\13\27\1\205\14\27"+
    "\24\0\1\27\5\0\2\27\3\0\15\27\1\206\12\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\207\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\210\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\12\27\1\211\15\27"+
    "\24\0\1\27\5\0\2\27\3\0\21\27\1\212\6\27"+
    "\24\0\1\27\5\0\2\27\3\0\23\27\1\213\4\27"+
    "\24\0\1\27\5\0\2\27\3\0\15\27\1\214\12\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\215\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\216\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\20\27\1\217\7\27"+
    "\24\0\1\27\5\0\2\27\3\0\1\27\1\220\26\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\221\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\1\27\1\222\26\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\223\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\11\27\1\224\16\27"+
    "\24\0\1\27\5\0\2\27\3\0\20\27\1\225\7\27"+
    "\24\0\1\27\5\0\2\27\3\0\11\27\1\226\16\27"+
    "\24\0\1\27\5\0\2\27\3\0\3\27\1\227\24\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\230\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\7\27\1\231\20\27"+
    "\24\0\1\27\5\0\2\27\3\0\14\27\1\232\13\27"+
    "\24\0\1\27\5\0\2\27\3\0\1\27\1\233\26\27"+
    "\24\0\1\27\5\0\2\27\3\0\13\27\1\234\14\27"+
    "\24\0\1\27\5\0\2\27\3\0\4\27\1\235\23\27"+
    "\24\0\1\27\5\0\2\27\3\0\14\27\1\236\13\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\237\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\7\27\1\240\20\27"+
    "\24\0\1\27\5\0\2\27\3\0\13\27\1\241\14\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\242\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\3\27\1\243\24\27"+
    "\24\0\1\27\5\0\2\27\3\0\3\27\1\244\24\27"+
    "\24\0\1\27\5\0\2\27\3\0\15\27\1\245\12\27"+
    "\24\0\1\27\5\0\2\27\3\0\3\27\1\246\24\27"+
    "\24\0\1\27\5\0\2\27\3\0\10\27\1\247\17\27"+
    "\24\0\1\27\5\0\2\27\3\0\15\27\1\250\12\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\251\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\21\27\1\252\6\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\253\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\254\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\15\27\1\255\12\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\256\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\257\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\15\27\1\260\12\27"+
    "\24\0\1\27\5\0\2\27\3\0\5\27\1\261\22\27"+
    "\24\0\1\27\5\0\2\27\3\0\22\27\1\262\5\27"+
    "\24\0\1\27\5\0\2\27\3\0\4\27\1\263\23\27"+
    "\24\0\1\27\5\0\2\27\3\0\21\27\1\264\6\27"+
    "\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6820];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\1\11\1\1\2\11"+
    "\2\1\1\11\1\1\1\11\2\1\3\11\1\1\1\11"+
    "\2\1\2\11\16\1\1\11\1\1\2\11\1\0\1\11"+
    "\1\0\6\11\1\1\1\11\1\0\1\11\32\1\1\11"+
    "\140\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private java.util.LinkedHashMap<Integer,String> tablaSimbolos = new java.util.LinkedHashMap<>();
    private int nextId = 1;

    private List<Object[]> listaTokens = new ArrayList<>();
    private List<Object[]> listaErrores = new ArrayList<>();

    private boolean simboloExiste(String simbolo) {
        return tablaSimbolos.containsValue(simbolo);
    }

    private void agregarSimbolo(String simbolo) {
        if (!simboloExiste(simbolo)) {
            tablaSimbolos.put(nextId++, simbolo);
        }
    }

    private void escribirTiraTokens(String token, String lexema){
        listaTokens.add(new Object[]{yyline + 1, lexema, token, yycolumn + 1});
    }

    private void escribirSimbolos(String simbolo){
        agregarSimbolo(simbolo);
    }

    private void escribirError(String lexema){
        listaErrores.add(new Object[]{"Error Lexico", lexema, yyline + 1, yycolumn + 1});
    }

    public List<Object[]> getTokens() {
        return listaTokens;
    }

    public List<Object[]> getErrores() {
        return listaErrores;
    }

    public List<Object[]> getSimbolos() {
        List<Object[]> result = new ArrayList<>();
        for (java.util.Map.Entry<Integer,String> e : tablaSimbolos.entrySet()) {
            result.add(new Object[]{e.getKey(), e.getValue()});
        }
        return result;
    }

    public void limpiarArchivos() {
        listaTokens.clear();
        listaErrores.clear();
        tablaSimbolos.clear();
        nextId = 1;
    }
    
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { escribirError(yytext());
            }
          // fall through
          case 65: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 66: break;
          case 3:
            { escribirTiraTokens("NOT", yytext()); return symbol(sym.NOT);
            }
          // fall through
          case 67: break;
          case 4:
            { escribirTiraTokens("MODULO", yytext()); return symbol(sym.MODULO);
            }
          // fall through
          case 68: break;
          case 5:
            { escribirTiraTokens("PARENTESIS_IZQ", yytext()); return symbol(sym.PARENTESIS_IZQ);
            }
          // fall through
          case 69: break;
          case 6:
            { escribirTiraTokens("PARENTESIS_DER", yytext()); return symbol(sym.PARENTESIS_DER);
            }
          // fall through
          case 70: break;
          case 7:
            { escribirTiraTokens("MULTIPLICACION", yytext()); return symbol(sym.MULTIPLICACION);
            }
          // fall through
          case 71: break;
          case 8:
            { escribirTiraTokens("SUMA", yytext()); return symbol(sym.SUMA);
            }
          // fall through
          case 72: break;
          case 9:
            { escribirTiraTokens("COMA", yytext()); return symbol(sym.COMA);
            }
          // fall through
          case 73: break;
          case 10:
            { escribirTiraTokens("RESTA", yytext()); return symbol(sym.RESTA);
            }
          // fall through
          case 74: break;
          case 11:
            { escribirTiraTokens("PUNTO", yytext()); return symbol(sym.PUNTO);
            }
          // fall through
          case 75: break;
          case 12:
            { escribirTiraTokens("DIVISION", yytext()); return symbol(sym.DIVISION);
            }
          // fall through
          case 76: break;
          case 13:
            { escribirTiraTokens("NUMERO_ENTERO", yytext()); 
    return symbol(sym.NUMERO_ENTERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 77: break;
          case 14:
            { escribirTiraTokens("DOS_PUNTOS", yytext()); return symbol(sym.DOS_PUNTOS);
            }
          // fall through
          case 78: break;
          case 15:
            { escribirTiraTokens("PUNTO_COMA", yytext()); return symbol(sym.PUNTO_COMA);
            }
          // fall through
          case 79: break;
          case 16:
            { escribirTiraTokens("MENOR_QUE", yytext()); return symbol(sym.MENOR_QUE);
            }
          // fall through
          case 80: break;
          case 17:
            { escribirTiraTokens("ASIGNACION", yytext()); return symbol(sym.ASIGNACION);
            }
          // fall through
          case 81: break;
          case 18:
            { escribirTiraTokens("MAYOR_QUE", yytext()); return symbol(sym.MAYOR_QUE);
            }
          // fall through
          case 82: break;
          case 19:
            { escribirTiraTokens("IDENTIFICADOR", yytext());
    escribirSimbolos(yytext());
    return symbol(sym.IDENTIFICADOR, yytext());
            }
          // fall through
          case 83: break;
          case 20:
            { escribirTiraTokens("CORCHETE_IZQ", yytext()); return symbol(sym.CORCHETE_IZQ);
            }
          // fall through
          case 84: break;
          case 21:
            { escribirTiraTokens("CORCHETE_DER", yytext()); return symbol(sym.CORCHETE_DER);
            }
          // fall through
          case 85: break;
          case 22:
            { escribirTiraTokens("LLAVE_IZQ", yytext()); return symbol(sym.LLAVE_IZQ);
            }
          // fall through
          case 86: break;
          case 23:
            { escribirTiraTokens("LLAVE_DER", yytext()); return symbol(sym.LLAVE_DER);
            }
          // fall through
          case 87: break;
          case 24:
            { escribirTiraTokens("DIFERENTE", yytext()); return symbol(sym.DIFERENTE);
            }
          // fall through
          case 88: break;
          case 25:
            { escribirTiraTokens("LITERAL", yytext()); 
    return symbol(sym.LITERAL, yytext());
            }
          // fall through
          case 89: break;
          case 26:
            { escribirTiraTokens("AND", yytext()); return symbol(sym.AND);
            }
          // fall through
          case 90: break;
          case 27:
            { escribirTiraTokens("ASIG_MULT", yytext()); return symbol(sym.ASIG_MULT);
            }
          // fall through
          case 91: break;
          case 28:
            { escribirTiraTokens("INCREMENTO", yytext()); return symbol(sym.INCREMENTO);
            }
          // fall through
          case 92: break;
          case 29:
            { escribirTiraTokens("ASIG_SUMA", yytext()); return symbol(sym.ASIG_SUMA);
            }
          // fall through
          case 93: break;
          case 30:
            { escribirTiraTokens("DECREMENTO", yytext()); return symbol(sym.DECREMENTO);
            }
          // fall through
          case 94: break;
          case 31:
            { escribirTiraTokens("ASIG_RESTA", yytext()); return symbol(sym.ASIG_RESTA);
            }
          // fall through
          case 95: break;
          case 32:
            { escribirTiraTokens("ASIG_DIV", yytext()); return symbol(sym.ASIG_DIV);
            }
          // fall through
          case 96: break;
          case 33:
            { escribirTiraTokens("IGUAL_IGUAL", yytext()); return symbol(sym.IGUAL_IGUAL);
            }
          // fall through
          case 97: break;
          case 34:
            { escribirTiraTokens("DO", yytext()); return symbol(sym.DO);
            }
          // fall through
          case 98: break;
          case 35:
            { escribirTiraTokens("IF", yytext()); return symbol(sym.IF);
            }
          // fall through
          case 99: break;
          case 36:
            { escribirTiraTokens("OR", yytext()); return symbol(sym.OR);
            }
          // fall through
          case 100: break;
          case 37:
            { escribirTiraTokens("NUMERO_FLOTANTE", yytext()); 
    return symbol(sym.NUMERO_FLOTANTE, Float.parseFloat(yytext()));
            }
          // fall through
          case 101: break;
          case 38:
            { escribirTiraTokens("FOR", yytext()); return symbol(sym.FOR);
            }
          // fall through
          case 102: break;
          case 39:
            { escribirTiraTokens("INT", yytext()); return symbol(sym.INT);
            }
          // fall through
          case 103: break;
          case 40:
            { escribirTiraTokens("NEW", yytext()); return symbol(sym.NEW);
            }
          // fall through
          case 104: break;
          case 41:
            { escribirTiraTokens("OUT", yytext()); return symbol(sym.OUT);
            }
          // fall through
          case 105: break;
          case 42:
            { escribirTiraTokens("CASE", yytext()); return symbol(sym.CASE);
            }
          // fall through
          case 106: break;
          case 43:
            { escribirTiraTokens("ELSE", yytext()); return symbol(sym.ELSE);
            }
          // fall through
          case 107: break;
          case 44:
            { escribirTiraTokens("MAIN", yytext()); return symbol(sym.MAIN);
            }
          // fall through
          case 108: break;
          case 45:
            { escribirTiraTokens("VOID", yytext()); return symbol(sym.VOID);
            }
          // fall through
          case 109: break;
          case 46:
            { escribirTiraTokens("BREAK", yytext()); return symbol(sym.BREAK);
            }
          // fall through
          case 110: break;
          case 47:
            { escribirTiraTokens("CLASS", yytext()); return symbol(sym.CLASS);
            }
          // fall through
          case 111: break;
          case 48:
            { escribirTiraTokens("FLOAT", yytext()); return symbol(sym.FLOAT);
            }
          // fall through
          case 112: break;
          case 49:
            { escribirTiraTokens("WHILE", yytext()); return symbol(sym.WHILE);
            }
          // fall through
          case 113: break;
          case 50:
            { escribirTiraTokens("STRING", yytext()); return symbol(sym.STRING);
            }
          // fall through
          case 114: break;
          case 51:
            { escribirTiraTokens("SYSTEM", yytext()); return symbol(sym.SYSTEM);
            }
          // fall through
          case 115: break;
          case 52:
            { escribirTiraTokens("IMPORT", yytext()); return symbol(sym.IMPORT);
            }
          // fall through
          case 116: break;
          case 53:
            { escribirTiraTokens("PUBLIC", yytext()); return symbol(sym.PUBLIC);
            }
          // fall through
          case 117: break;
          case 54:
            { escribirTiraTokens("RETURN", yytext()); return symbol(sym.RETURN);
            }
          // fall through
          case 118: break;
          case 55:
            { escribirTiraTokens("STATIC", yytext()); return symbol(sym.STATIC);
            }
          // fall through
          case 119: break;
          case 56:
            { escribirTiraTokens("SWITCH", yytext()); return symbol(sym.SWITCH);
            }
          // fall through
          case 120: break;
          case 57:
            { escribirTiraTokens("BOOLEAN", yytext()); return symbol(sym.BOOLEAN);
            }
          // fall through
          case 121: break;
          case 58:
            { escribirTiraTokens("DEFAULT", yytext()); return symbol(sym.DEFAULT);
            }
          // fall through
          case 122: break;
          case 59:
            { escribirTiraTokens("EXTENDS", yytext()); return symbol(sym.EXTENDS);
            }
          // fall through
          case 123: break;
          case 60:
            { escribirTiraTokens("PACKAGE", yytext()); return symbol(sym.PACKAGE);
            }
          // fall through
          case 124: break;
          case 61:
            { escribirTiraTokens("PRINTLN", yytext()); return symbol(sym.PRINTLN);
            }
          // fall through
          case 125: break;
          case 62:
            { escribirTiraTokens("PRIVATE", yytext()); return symbol(sym.PRIVATE);
            }
          // fall through
          case 126: break;
          case 63:
            { escribirTiraTokens("PROTECTED", yytext()); return symbol(sym.PROTECTED);
            }
          // fall through
          case 127: break;
          case 64:
            { escribirTiraTokens("IMPLEMENTS", yytext()); return symbol(sym.IMPLEMENTS);
            }
          // fall through
          case 128: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
